### ISSUE TITLE
Italics alignment issue in Sublime Text

### ISSUE THREAD

**Issue by nikitaourazbaev** [MonoLisaFont/feedback#154]
## Background information

To help debugging, fill the following information before describing the issue:

* Font edition (i.e. trial, personal, plus, pro): plus
* Font version (i.e. 1.805): 1.808
* The type of the font file you are using (i.e. otf, ttf): otf
* Operating system (i.e. MacOS, Windows): macOS
* Display resolution (i.e. 3072x1920): 2048 x 1152 @ 2x (4096 x 2304)
* Any other information that might be helpful: This is happening in Sublime Text 4126, this does not seem to happen in VS Code

## Issue

If part of a line is using italics it seems to overflow onto the non-italic text that follows. When this happens, the cursor no longer reflects the current insertion point and editing text becomes tricky.

![MonoLisa 1.808](https://user-images.githubusercontent.com/41582891/171282617-93d94534-d19d-446f-95ce-ab39d5455965.png)

_MonoLisa 1.808_

Here's how Operator Mono and Fira Code render the same code snippet:

![Operator Mono](https://user-images.githubusercontent.com/41582891/171282474-1e4a68b2-0aea-4e1d-a59a-ee307b8d499a.png)

_Operator Mono_

![Fira Code](https://user-images.githubusercontent.com/41582891/171282752-9ca9f5a8-ff92-47bc-a444-70f20e6eb87d.png)

_Fira Code_

**Comment by dwhenson** [comment]
Just came here to raise the same issue - thanks!

**Comment by bebraw** [comment]
Can you provide a minimal text snippet to paste into Sublime to test? I would also need your exact font configuration in Sublime Text as I was unable to reproduce the issue.

**Comment by dwhenson** [comment]
I can try, this should show the issue: 

  --clr-primary-300: hsl(31, 100%, 65%);
 // Colon between propterty and value is hidden under preceding '0'

  color: var(--clr-neutral-300);
 // Final bracket hidden under preceding '0'

I'm not sure what font configuration you need but I have the following in my settings file:

 "font_face": "MonoLisa",  
  "font_size": 16,

Please let me know if you need any additional information. I am using the script variant as per the screenshot attached. 
<img width="553" alt="Screenshot 2022-06-17 at 14 44 31" src="https://user-images.githubusercontent.com/50716370/174292102-f937f764-411f-4791-8ec4-fd85a34dc105.png">

**Comment by bebraw** [comment]
How did you enable the script feature in sublime? Did you use the customize tool for that?

It's starting to feel like that the issue is specific to that. Can you confirm that it renders correctly with a regular italic?

**Comment by dwhenson** [comment]
I don't have regular italic, I downloaded the custom font set and the script variant as my italic version. 

The script version worked fine on previous releases of the font. 

I don't really want to re-download and install the fonts to test that out. If you want me to do that let me know and I'll set aside some time to do it.

**Comment by bebraw** [comment]
No probs. That's good info I think.

**Comment by nikitaourazbaev** [comment]
Apologies for not replying sooner, I was away last week.

This happens with both the script italic (custom download, no OT freezing) and the regular italic. The italic in the screenshot in my original report is the regular italic.

The italics are being applied by the Monokai Pro theme:

https://monokai.pro/

I’m not sure the issue is with how the italics are being applied because Operator and Fira don't exhibit the spacing issue when switching between italics and regular text. 

My font settings are:

```
{
  "font_size": 14.0,
  "font_face": "MonoLisa",
  "font_options": ["no_calt", "no_liga", "ss02"]
}
```

Let me know if I can provide any additional info.

**Comment by bebraw** [comment]
Can you see the issue with other themes? I was testing with the default theme of Sublime. I wonder if that's the problem.

To test, I would need a free theme or minimal theme declaration that can be used to reproduce the issue.

**Comment by nikitaourazbaev** [comment]
Hmm, actually, no, I can't see the issue with other themes. I had noticed this but chalked it up to other themes not italicizing as many tokens that can be long. I tried a longer CSS property name with Sublime’s default theme and can't see the issue:

![CleanShot 2022-06-20 at 14 53 12@2x](https://user-images.githubusercontent.com/41582891/174663253-da76eae8-86a1-421f-bd4e-b5f7239742a1.png)

I will try to figure out how Monokai Pro sets italics and will post an update once I do, hopefully today or tomorrow.

Monokai Pro has an indefinite free evaluation period, similar to Sublime Text, and can be installed from Package Control:

```
Package Control > Install Package > Theme - Monokai Pro

Command Palette > Monokai Pro: select theme
```

**Comment by nikitaourazbaev** [comment]
A quick update on the above: I tried some other longer CSS property names and I can see a little bit of the issue, though not nearly to the same extent:

![CleanShot 2022-06-20 at 14 58 54@2x](https://user-images.githubusercontent.com/41582891/174663863-7bba1993-9178-43c6-89e1-def0cdad376c.png)

The colon does seem to be a little close to the italic text but it doesn't get worse the more characters there are.

**Comment by bebraw** [comment]
@nikitaourazbaev Thanks, that helped a lot.

I was able to find out that the issue actually has to do with the wrong width of `-`. It's the same issue as #152 and that has been fixed already. The fix will be available in the next release.

**Comment by dwhenson** [comment]
Thanks for this guys. Look forward to the fix in the next release.

**Comment by nikitaourazbaev** [comment]
@bebraw Has this fix made it into the 2.0.0 pre-release version that’s currently available for download by any chance? Just curious as I’m still seeing this issue here with that version.

**Comment by bebraw** [comment]
The fix is in the variable version of the prerelease. 

The version with the separate files might miss it (waiting for a build).

**Comment by nikitaourazbaev** [comment]
Ahh yes, the variable version works perfectly, thank you!

**Comment by bebraw** [comment]
2.0 is officially available with the fix.
