### ISSUE TITLE
[Bug]: Monolisa 2.013 Character Spacing not shown correctly on Terminal App

### ISSUE THREAD

**Issue by Pyre909** [MonoLisaFont/feedback#268]
### Edition

Plus

### What version are you using?

2.013

### What type of weights are you using?

Default (non-customized)

### Operating system

Windows 10 Pro 22H2

### Program

Putty(Terminal)

### Display resolution

3840x2160

### What happened?

Installed font and used in Terminal(Putty) and the character spacing is abnormally long in the terminal. Screenshots attached from how the font displays text on the Editor and the Terminal where the issue is seen.

<img width="1009" alt="Terminal_Render" src="https://github.com/MonoLisaFont/feedback/assets/3960786/0b90217a-28bc-40df-91db-ee57724ce945">
<img width="523" alt="TextEditor_Render" src="https://github.com/MonoLisaFont/feedback/assets/3960786/e8a20c05-7be9-4e95-a41e-3ebf5cd43650">

**Comment by Pyre909** [comment]
This is happening for every font variation as well.

**Comment by bebraw** [comment]
I have trouble reproducing this under MacOS so I imagine it might be a Windows specific issue to debug.

Can you see the issue in other terminals under Windows?

**Comment by Pyre909** [comment]
Looks like this might be specific to Putty. Font displays normal rendering using Command Prompt or Windows Terminal. I should note that this didn't happen on 2.012

**Comment by bebraw** [comment]
I wonder what changed in between. Maybe it's some difference in font metadata or so.

**Comment by bebraw** [comment]
When you have time, can you check if the latest prerelease has the issue? When downloading, make sure to choose `prerelease` channel.

**Comment by Pyre909** [comment]
Hi , Same issue on the pre-release version when used in putty.

**Comment by bebraw** [comment]
Thanks for testing! Maybe we still missed something (cc @MarcusSterz).

**Comment by mekkablue** [comment]
There’s a bug in Glyphs 3.2 where `OS/2.xAvgCharWidth` is always exported as 0, but should be 640. Fixed in the upcoming version (both app and font).

**Comment by bebraw** [comment]
@Pyre909 There's a new version with the fix to test now.

**Comment by Pyre909** [comment]
@bebraw just tested the pre-release version issue still persists.

**Comment by bebraw** [comment]
@Pyre909 Thanks for testing!

@mekkablue Could something be off in the current prerelease version? Note that the issue is visible only within Terminal(Putty) under Windows.

**Comment by MarcusSterz** [comment]
As @mekkablue wrote it's a current bug in Glyphs. Once that's fixed we can ship a version that works in Putty. 
Until then please use v2.012.

**Comment by bebraw** [comment]
@Pyre909 We applied the Glyphs side fix. When you have a good moment, please give the prerelease a go.

**Comment by Pyre909** [comment]
@bebraw The fix worked. Thanks!

**Comment by bebraw** [comment]
Fixed in 2.014.
