### ISSUE TITLE
Linux - JetBrains Rider - Only "MonoLisa Bold" is shown in the monospaced font list

### ISSUE THREAD

**Issue by bebraw** [MonoLisaFont/feedback#42]
See gif below:

![monolisa](https://user-images.githubusercontent.com/166921/97216941-36345300-17cf-11eb-9c1d-6a347a99a1f1.gif)

The correct behavior would be to show "MonoLisa Regular" and possible other options as well in addition to "MonoLisa Bold".

**Comment by MarcusSterz** [comment]
@mekkablue Can you have a look?

**Comment by mekkablue** [comment]
Which OS?

**Comment by bebraw** [comment]
@mekkablue It looks like some Windows or Linux but I'll ask the reporter to know for sure. I wonder if the issue is specific to this specific IDE. Could it be that some metadata is off or can the issue be on their side?

**Comment by lzybkr** [comment]
This is Windows 10. I wouldn't rule out anything, but I reported the issue here first because one of the styles is handled correctly.

**Comment by bebraw** [comment]
Based on a user, this occurs in PhpStorm as well on Windows.

**Comment by TiiFuchs** [comment]
> Based on a user, this occurs in PhpStorm as well on Windows.

That user be me, so if there are any further questions. I'm happy if I can assist in some way. :)

**Comment by bebraw** [comment]
@TiiFuchs Note that workaround shown in the gif - you can select `MonoLisa` if you uncheck the "show monospaced fonts". Somehow it seems to get categorized wrongly.

**Comment by TiiFuchs** [comment]
@bebraw Good to know. That worked. Thanks for the workaround! :)

**Comment by MarcusSterz** [comment]
@mekkablue Any idea what could be the problem?

**Comment by mekkablue** [comment]
I could not replicate the menu issue exactly like in the screenshots. But something similar: It displayed te regular MonoLisa _and_ the Bold Italic in the menu

Will try again with 1.60X and introduce PANOSE settings, perhaps the app scans for those.

**Comment by bebraw** [comment]
@mekkablue I tested the fixed version with PANOSE settings under Windows 10. It seems adding that metadata doesn't fix the issue.

I found out that you can see the faulty name even in Windows 10 itself if you navigate to `C:\Windows\Fonts`. It shows the font family name as `MonoLisa Bold` there and I believe it's possible JetBrains editors pick up the name from the system level so the issue may not be restricted to that specific editor.

I'm not sure if it's related but `MonoLisa Bold` is the first font on the list of files when they are sorted alphabetically. Is it possible Windows is picking up the name from there somehow?

**Comment by bebraw** [comment]
@mekkablue To provide more info, I tested using the ttf format (copied over to the Fonts directory) with the Plus package.

Likely the main thing would be to get the issue reproduce for you under Windows 10. As mentioned above, you should be able to see the wrong name in Windows itself.

**Comment by bebraw** [comment]
@mekkablue I have more info. I found this service: https://fontdrop.info/ . Check out the output for MonoLisa Black:

<img width="536" alt="Screen Shot 2021-01-22 at 15 39 55" src="https://user-images.githubusercontent.com/166921/105504559-2fcb4f80-5cc8-11eb-9411-4c67f05fd680.png">

Here's Fira Code for comparison (otf, though):

<img width="534" alt="Screen Shot 2021-01-22 at 15 41 14" src="https://user-images.githubusercontent.com/166921/105504652-4d98b480-5cc8-11eb-8bea-2dc92a7e87ff.png">

If I'm interpreting correctly, the `fontFamily` field is set wrongly for MonoLisa under ttf. It should be simply `MonoLisa` instead of `MonoLisa Black`. I imagine that's what Windows is using for grouping the fonts. Could that be it?

**Comment by mekkablue** [comment]
No. You compared a RIBBI font with a non-RIBBI font. What you suggest only applies to a RIBBI font.

**Comment by bebraw** [comment]
Ok, regardless it's maybe worth checking the font metadata.

I guess ideally you would have Windows 10 available somehow. Even a virtual machine is enough for testing this and you won't need even JetBrains to see the behavior as it's visible in Windows itself.

**Comment by mekkablue** [comment]
The RIBBI style linking was wrong for Bold Italic and Black Italic 1.602. Fixed in my most recent commit.

**Comment by bebraw** [comment]
@mekkablue Cool to hear you found a fix. 👍

**Comment by ninthspace** [comment]
I still have this issue with 1.603 and PhpStorm. Below screenshot illustrates that assigning anything Bold makes the corresponding text appear as Bold Italic. I'm also trying to diagnose with JetBrains' assistance. https://youtrack.jetbrains.com/issue/IDEA-262765

![Screenshot from 2021-03-09 09-33-21](https://user-images.githubusercontent.com/248954/110449860-88a94880-80ba-11eb-85f4-774426fa6134.png)

My OS is Zorin 15.3.

**Comment by nashpatty** [comment]
Also having a similar issue in PHPStorm 2021.1.2. But in my case, MonoLisa isn't showing up in the fonts list at all.
Works great in VSCode and windows terminal etc.

**Comment by dinhquochan** [comment]
@nashpatty  what's your OS? In below screenshot, in Manjaro with PhpStorm 2021.1.2, It's showing properly. Let's try download newest version, remove/uninstall old fonts and re-install.


![image](https://user-images.githubusercontent.com/9979458/118579953-302cb080-b7b9-11eb-99d6-b97268af3ff0.png)

**Comment by nashpatty** [comment]
> @nashpatty what's your OS? In below screenshot, in Manjaro with PhpStorm 2021.1.2, It's showing properly. Let's try download newest version, remove/uninstall old fonts and re-install.
> 
> ![image](https://user-images.githubusercontent.com/9979458/118579953-302cb080-b7b9-11eb-99d6-b97268af3ff0.png)

I'm on windows. I installed the OTF version before. I uninstalled and reinstalled TTF, and it shows up again.
Is there a discrepancy for windows/OTF? It was working in everything but PhpStorm.

**Comment by dinhquochan** [comment]
@nashpatty @bebraw Just Install OTF version on JetBrains Raider (Windows 10), Do both restart editor and os, but doesn't see MonoLisa on fonts panel. But I remove OTF version and install TTF version, It's worked!

![image](https://user-images.githubusercontent.com/9979458/118756305-d3062d00-b894-11eb-9587-ee12cac48138.png)

**Comment by dinhquochan** [comment]
Just update the issue, I install latest version (1.801), Windows Jetbrain Rider still ugly.

![image](https://user-images.githubusercontent.com/9979458/126677320-b26ed028-e67b-4559-a97d-b099b0435b12.png)

Below, Jetbrains Mono:

![image](https://user-images.githubusercontent.com/9979458/126677406-ef5fff65-2a89-48db-86db-ae6c9bfe4fb1.png)

**Comment by dinhquochan** [comment]
I think it is a Windows issue, Windows programs prefer TTF over OTF. Especially the Java ones. It's a weird issue on HiDPI 🤦‍♂️
Below, just remove OTF version and install TFF version.

![image](https://user-images.githubusercontent.com/9979458/126682648-e9747049-df5c-4184-a2de-fda7e9f80625.png)

Ref [tonsky/FiraCode#693](https://github.com/tonsky/FiraCode/issues/693).

**Comment by bebraw** [comment]
Let's close as a solution was found. To solve, please use TTF on Windows.
