### ISSUE TITLE
Vertical align issue on Powerline

### ISSUE THREAD

**Issue by dongheeleeme** [MonoLisaFont/feedback#96]
Hi team,

Hi! I'm using MonoLisa font on Terminal but as we can see the powerline fonts are not aligned in the status line. Can we fix this issue as an updated version?

Thank you! 

<img width="657" alt="Screenshot 2021-09-03 at 21 12 20" src="https://user-images.githubusercontent.com/38916112/132056102-7a8a206e-2d35-46f0-a4a0-0155c1ffd4fa.png">

**Comment by okonet** [comment]
@MarcusSterz i guess it might be the line height which is a bit bigger in ML. Could you take a look please?

**Comment by dongheeleeme** [comment]
Thank you for the reply @okonet. I'm using default line height and I think It should be displayed correctly without changing any configurations.

**Comment by dinhquochan** [comment]
![image](https://user-images.githubusercontent.com/9979458/132104157-6e821335-f3ce-4244-97dc-02ef3e8590cc.png)

**Comment by MarcusSterz** [comment]
Had a look at it and it will be fixed with the next update

**Comment by MarcusSterz** [comment]
@dinhquochan 🤔 Interesting that you see it differently. I can confirm that the block and the arrow element are slightly missaligned.

**Comment by dongheeleeme** [comment]
Thank you @MarcusSterz 🙇‍♂️  Then, Can I know the next release date?

**Comment by okonet** [comment]
We don’t have the release date yet but you will get an email if you have us a consent while purchasing. Otherwise follow us on Twitter please.

**Comment by bebraw** [comment]
Fixed in 1.802.

**Comment by okonet** [comment]
Interestingly I still experience issues with the latest `1.808`:
<img width="252" alt="CleanShot 2022-03-31 at 09 33 07@2x" src="https://user-images.githubusercontent.com/11071/161002060-3e839c2d-2520-4b9e-8681-c95a3d83c85b.png">

<img width="350" alt="image" src="https://user-images.githubusercontent.com/11071/161002030-044a72ac-58ad-41b9-b1c0-dde66a7da2dd.png">

There are also weird issues with colors but I'm not sure it's the font:

<img width="350" alt="image" src="https://user-images.githubusercontent.com/11071/161002145-70d5acc4-1c1c-456f-9417-2b1dff5f60b4.png">

I'm using `bhilburn/powerlevel9k` as a theme and have set font size to 15px but it looks similar with 14px:

<img width="350" alt="image" src="https://user-images.githubusercontent.com/11071/161002305-2c16eca8-f9d5-450b-a056-1834fd137da8.png">

<img width="350" alt="image" src="https://user-images.githubusercontent.com/11071/161002339-8096c243-b074-4e9e-aa03-31196bc84093.png">

**Comment by bebraw** [comment]
Let's re-open so this can be checked again.

**Comment by bebraw** [comment]
My renders below:

**1.806**

<img width="121" alt="Screen Shot 2022-03-31 at 10 54 25" src="https://user-images.githubusercontent.com/166921/161005734-6e552ffd-5495-4dd0-ad00-6b6535dfb25d.png">
<img width="66" alt="Screen Shot 2022-03-31 at 10 54 21" src="https://user-images.githubusercontent.com/166921/161005737-c2031e60-2a92-4da2-957c-8bed3ecf5286.png">

**1.808**

<img width="148" alt="Screen Shot 2022-03-31 at 10 56 23" src="https://user-images.githubusercontent.com/166921/161006077-24bec6ea-5264-4293-8e51-c7f53ce642a2.png">
<img width="61" alt="Screen Shot 2022-03-31 at 10 56 19" src="https://user-images.githubusercontent.com/166921/161006080-8240232c-12dd-43c8-b978-2234a88f8c16.png">

Technically 1.806 and 1.808 are the same as it was only ttf fixes and I use only otf.

**Comment by bebraw** [comment]
It's size 11 on a 3072x1920 display. With that resolution the alignment is acceptable as normally you don't look at it very close.

**Comment by MarcusSterz** [comment]
I have a adjusted the heights of the traingles to the block symbols. The latters had been altered previeously due to consistency with border symbols. It’s all connected... 8-/

Will be visible in the next update.

**Comment by bebraw** [comment]
Included in 2.0.

**Comment by dongheeleeme** [comment]
Hi @okonet, I need your favor. Could you please delete issue?

**Comment by okonet** [comment]
AFAIK issues cannot be deleted. Why would you want us to delete it?

**Comment by dongheeleeme** [comment]
Hi @okonet, I thought this issue is not related to font itself. It's different by terminals. I thought that it's better to delete this issue in order to do not make any confusion for others.
